### ISSUE TITLE
Error in mysql_connect() function

### ISSUE THREAD

**Issue by DanAnonymous** [gatechgrad/LeaderboardExample#1]
I already uploaded php  to web server page. and open it ,then show up this error:
Uncaught Error: Call to undefined function mysql_connect()

**Comment by levidsmith** [comment]
Looks like mysql_connect was removed in PHP 7.
https://secure.php.net/manual/en/function.mysql-connect.php

**Comment by levidsmith** [comment]
I have updated all mysql_ calls with mysqli_ calls in the latest commit.  This should resolve issues with newer versions of PHP.
